### ISSUE TITLE
can be this be compiled on ESP32 ?

### ISSUE THREAD

**Issue by plkumar** [maximkulkin/esp-homekit-demo#18]
Can this be complied to work on ESP32? what changes needs to be done?

**Comment by renssies** [comment]
No, this will not work directly on ESP32 because esp-open-sdk and esp-open-rtos don't work on ESP32 (yet). 

There are however people working on an ESP32 version of this library using the official ESP32 SDK. You can also find these on GitHub. The last time I checked they didn't work yet, they compile but most of them don't have the HomeKit pairing built yet.

**Comment by jukorp** [comment]
I am very interested in esp32 and nrf52.
These are much quicker.
Esp idf. Can you build with this?

Resources should be directed to this new esp32 chip.

**Comment by faronov** [comment]
https://github.com/aanon4/HomeKit nrf51 and nrf52 repo

**Comment by maximkulkin** [comment]
So, currently the answer is NO. Closing this. You can proceed with further discussion in #23.
