### ISSUE TITLE
Bluetooth instead of WiFi on ESP32

### ISSUE THREAD

**Issue by planetk** [maximkulkin/esp-homekit-demo#267]
Hi,

first thank you for this great piece of Software. I wonder if it would be possible to pair ESP32 based Devices via Bluetooth instead of WiFi?

Kind regards
Stefan

**Comment by maximkulkin** [comment]
I had a plan to make a bluetooth version, hoping that low-energy bluetooth would allow HomeKit devices to run on batteries. But since Espressif gave up on low-energy part, I have not incentive to do that: it's a lot of work with no apparent benefit: ESP32 devices are much less ubiquitous as ESP8266.
