### ISSUE TITLE
How to change de Lock example?

### ISSUE THREAD

**Issue by MizzyAntunes** [maximkulkin/esp-homekit-demo#318]
I would like to use the "Lock" model of the examples, but I don't want it to lock itself after a few seconds. How can I change this?

**Comment by maximkulkin** [comment]
By modifying the code

**Comment by pocketscience** [comment]
That's what I'd do too... maybe starting with disabling the timer that does the auto-locking after unlock_period seconds...

**Comment by MizzyAntunes** [comment]
> By modifying the code

I know, but I don't know how to do that, because I'm a noob. I think someone who knows programming would know how to help me

**Comment by MizzyAntunes** [comment]
> That's what I'd do too... maybe starting with disabling the timer that does the auto-locking after unlock_period seconds...

Ok, tks

**Comment by pocketscience** [comment]
You might want to think about some basic programming courses instead of jumping head-first into embedded development. There's a lot to learn just on the programming side, let alone all the intricacies of embedded systems. If you're after a HomeKit lock in the meantime it might be simpler to buy one... Sorry, not trying to be rude - just people here are going to struggle to help you through every single step - especially when you ask such basic questions as these and others... Help yourself first, then others might be more willing to provide more assistance.

**Comment by MizzyAntunes** [comment]
> You might want to think about some basic programming courses instead of jumping head-first into embedded development. There's a lot to learn just on the programming side, let alone all the intricacies of embedded systems. If you're after a HomeKit lock in the meantime it might be simpler to buy one... Sorry, not trying to be rude - just people here are going to struggle to help you through every single step - especially when you ask such basic questions as these and others... Help yourself first, then others might be more willing to provide more assistance.

ok, I understand, is that my interest was only in the homekit. Excuse me
