### ISSUE TITLE
Controlling the led with a button

### ISSUE THREAD

**Issue by EzDzO** [maximkulkin/esp-homekit-demo#4]
Hi, you should add the possibility to turn on or off using a button. 
Something like [this](https://github.com/HomeACcessoryKid/ESP8266-HomeKit-Demo/tree/master/button-led)

**Comment by maximkulkin** [comment]
Interfacing with a button should not be hard (see [this button example](https://github.com/SuperHouse/esp-open-rtos/blob/master/examples/button/button.c)). I will leave it as an exercise for users. From HomeKit standpoint it's like combination of LED example (where state is fully controlled from outside of accessory) and temperature sensor (where accessory changes state and broadcasts notifications to all currently connected controllers).

**Comment by HomeACcessoryKid** [comment]
In itself, it seems valid, but the need to (re)define the CURRENT_TEMPERATURE char seems a bit cumbersome. Some improvement in that field would be nice.
Maybe to have a .pusher besides a .setter and .getter to bridge that gap??

**Comment by HomeACcessoryKid** [comment]
OK, a .pusher is missing the point of course. But we could have an item in the accessories struct that can be set to a pointer we declare ourselves of the home kit_characteristic_t, just like temperature is in the demo now.
the homekit_server_init can then set the pointer to point to where the characteristic is stored internally. All that is left to do is call:
```
temperature.float_value = hwrand() % 100;
homekit_characteristic_notify(&temperature);
```
without the need to setup that struct all by ourselves. All those attributes it has are predetermined by apple anyway so best left standard.

**Comment by maximkulkin** [comment]
First of all, while there are characteristics defined by Apple, framework should leave the room to define custom characteristics and would be nice if both are done in the same way. Also, as is outlined in Apple's HomeKit specification, values of some properties for some Apple defined characteristics "MAY be modified in order to better fit the specific application". Such properties include minimum/maximum values, step value, maximum length and maximum data length. So, even if you use characteristic like "Current Temperature", you can set minimum/maximum values to whatever you need. E.g. Apple specifies them as 0-100 degrees Celsius, but if you have sensor that can meauser negative temperature, you can override those.

So, in addition to providing uniform way to define both predefined and custom characteristics and overrides, the structures were designed as they are now.

Building a library of predefined characteristics is a planned thing but is not top priority. I would greatly appreciate if someone would volunteer to define all them and send PR. But, again, even if some characteristic is not there yet, it should not block users from using them, they just need to define those characteristic's themselves in their apps.

PS Not sure I understand the usecase with .pusher. What .pusher supposed to mean/do?

**Comment by HomeACcessoryKid** [comment]
Probably with pusher I meant handle, see below...

we could have an item called ```.handle``` in the accessories struct that can be set to a pointer we declare ourselves of the homekit_characteristic_t, just like temperature is in the demo now.
the homekit_server_init can then set the pointer to point to where the characteristic is stored internally. 
The way the service would be setup is
```
            homekit_characteristic_t temperature;
            HOMEKIT_DECLARE_CHARACTERISTIC_NAME("Sample LED"),
            HOMEKIT_DECLARE_CHARACTERISTIC_CURRENT_TEMPERATURE(
                .handle=temperature
            ),
```

All that is left to do is call:
```
temperature.float_value = hwrand() % 100;
homekit_characteristic_notify(&temperature);
```
without the need to setup that characteristic all by ourselves. 

I leave it to you to figure out where to put * and & which is my least favourite hobby ;-)

**Comment by maximkulkin** [comment]
How is it different from current plan:
```c
homekit_characteristic_t *temperature = HOMEKIT_DECLARE_CHARACTERISTIC_CURRENT_TEMPERATURE(
    .getter = get_current_temperature,
);

homekit_accessory_t *accessories[] = {
    HOMEKIT_ACCESSORY(.id=1, .services={
        // ...
        HOMEKIT_SERVICE(HOMEKIT_SERVICE_TEMPERATURE_SENSOR, .characteristics={
            HOMEKIT_DECLARE_CHARACTERISTIC_NAME("My temperature sensor"),
            temperature
        })
    }),
    NULL
}
```

**Comment by maximkulkin** [comment]
Not sure if subsequent discussion is relevant, but original question was to control an LED with a button. While I do not see a reason to implement each and every example in other projects, there is an example for LED and I have recently added a separate example for button. Thus I think this issue can be closed.
