### ISSUE TITLE
Web Server for configuration

### ISSUE THREAD

**Issue by ageorgios** [maximkulkin/esp-homekit-demo#46]
Hello I have implemented a motor example
https://github.com/ageorgios/esp-homekit-motor

And would like to hear feedback how to implement an HTTP Server in order to change variables and configuration of the accessory.

I know this goes out of the spec of Homekit, but with Homekit there is no way to create a generic implementation of a motor and then configure it.

Thank you.

**Comment by renssies** [comment]
Instead of an HTTP server, you could implement a custom service with custom characteristics for the configuration. I don't have an example atm, but I'm sure @maximkulkin or someone else can help you. 

Apps like Elgato Eve and Home (by Matthias) support simple custom services and characteristics. Especially things like a bool or an int.

**Comment by RavenSystem** [comment]
I agree with @renssies . It's better use a custom service with your own characteristics, and then use ElGato App to configure it. I recommend you to use the HomeKit Accessory Simulator, included in Hardware IO Tools for Xcode (https://developer.apple.com/download/more/), to play with custom services, so you can see what are your possibilities to implement them. Running another HTTP server in the accessory is not a good idea due to low resources of ESP8266.

**Comment by ageorgios** [comment]
You pursuaded me,
an example from @maximkulkin would be great!

**Comment by maximkulkin** [comment]
1. Generate yourself an UUID:
```shell
uuid
# => abe0ecb2-1cc8-11e8-a58f-3f83472d9d7e
```
2. Change leading group to all zeros and then use it as a base for your own characteristic IDs, e.g. `00000000-1cc8-11e8-a58f-3f83472d9d7e`.
3. Declare your own services and characteristics:
```c

#define MY_UUID(value) (value "-1cc8-11e8-a58f-3f83472d9d7e")
#define HOMEKIT_SERVICE_FOO MY_UUID("00000001")
#define HOMEKIT_CHARACTERISTIC_BAR MY_UUID("00000002")
#define HOMEKIT_DECLARE_CHARACTERISTIC_BAR(_value, ...) \
    .type = HOMEKIT_CHARACTERISTIC_BAR, \
    .description = "Bar", \
    .format = homekit_format_uint8, \
    .permissions = homekit_permissions_paired_read \
                 | homekit_permissions_paired_write \
                 | homekit_permissions_notify, \
    .value = HOMEKIT_UINT8_(_value), \
    ##__VA_ARGS__

#define HOMEKIT_CHARACTERISTIC_BAZ MY_UUID("00000003")
#define HOMEKIT_DECLARE_CHARACTERISTIC_BAZ(_value, ...) \
    .type = HOMEKIT_CHARACTERISTIC_BAZ, \
    .description = "Baz", \
    .format = homekit_format_bool, \
    .permissions = homekit_permissions_paired_read \
                 | homekit_permissions_paired_write \
                 | homekit_permissions_notify, \
    .value = HOMEKIT_BOOL_(_value), \
    ##__VA_ARGS__

// ...

HOMEKIT_SERVICE(FOO, .characteristics=(homekit_characteristic_t*[]) {
    HOMEKIT_CHARACTERISTIC(BAR, 123),
    HOMEKIT_CHARACTERISTIC(BAZ, true),
    NULL
})
```
